# Use official PostgreSQL 18 image
FROM postgres:18

# Set environment variables for default database
ENV POSTGRES_DB=parrot_social_db
ENV POSTGRES_USER=parrot_db_user
ENV POSTGRES_PASSWORD=parrot_db_pass

# Expose PostgreSQL port
EXPOSE 5432